enable dma for USART in stm32f302. fix hal! implementation for USART3, 4 for stm32f3
stm32-rs/stm32f3xx-hal pull request #135
Opened 2020-09-01 15:36 UTC by sprhawk

2020-09-01 15:38 UTC, sprhawk commented
it can build, but failed to run dma serial transfer on my stm32f302r8 device. I think it should not be caused by changes here. I pushed it for reviewing first

2020-09-03 07:44 UTC, strom-und-spiele commented
Thanks for your work!

> it can build, but failed to run dma serial transfer on my stm32f302r8 device ( transferring garbage data). I think it should not be caused by changes here. I pushed it for reviewing first

I don't really get how one can help you here. Do you want a review on the working code or help making the DMA work?

2020-09-03 08:40 UTC, ra-kete commented
I also think you'll have an easier time finding people willing to review if you made sure all the CI checks pass first. At least speaking for myself, when I see those failing checks I automatically assume this PR is not worth reviewing yet since I would only find the same issues the CI has already found.

If you have any specific problems we can help you out with, let us know. But as @strom-und-spiele implied, nobody is going to be able to help you much with figuring out what breaks DMA on your F302, since nobody owns that hardware AFAIK.

2020-09-09 18:14 UTC, ra-kete requested changes
Looks reasonable, just a few style requests.

2020-09-09 18:14 UTC, ra-kete commented on src/dma.rs
> +#[cfg(any(feature = "stm32f303", feature = "stm32f302"))]
Actually I think this whole `#[cfg]` isn't needed at all. Since we already have the gate in lib.rs.

2020-09-09 18:14 UTC, ra-kete commented on src/lib.rs
> +#[cfg(any(feature = "stm32f303", feature = "stm32f302"))]
Nit: 302 should come before 303
(Also applies to the other instances of this in this PR)

2020-09-10 05:10 UTC, ra-kete approved these changes
LGTM. Can you also add a changelog entry?

2020-09-10 06:09 UTC, sprhawk commented
> Looks like you accidentally duplicated this one.

They are different PRs, Should I merge them into one with some text?

2020-09-10 06:19 UTC, ra-kete commented
No, just remove the second entry for #132 from the changelog. It's already there (two lines above).

2020-09-10 08:15 UTC, sprhawk commented
I have dropped my last commit and forcely pushed

2020-09-10 08:29 UTC, ra-kete commented
Hm, now the diff contains changes from other PRs too, that are actually already in master. Not sure what went wrong here. Let me try if I can fix it once I'm back at a PC.

2020-09-10 09:03 UTC, sprhawk commented
> Hm, now the diff contains changes from other PRs too, that are actually already in master. Not sure what went wrong here. Let me try if I can fix it once I'm back at a PC.

Because I merge from the upstream, or else, github will not allow merge.

2020-09-11 10:36 UTC, closed without merging

2020-09-11 10:51 UTC, ra-kete commented
Sorry, I meant to push my fixup changes to your branch but pushed my master branch instead. This caused an empty diff on this PR, which lead Github to automatically close it. As long as the PR is closed I cannot push to your branch to fix my mistake and as long as the diff is empty I cannot re-open the PR. I took the simple solution of opening a new PR with these changes. Please check out #139. If it looks good to you, I will merge it.

2020-09-11 12:12 UTC, sprhawk commented
> Sorry, I meant to push my fixup changes to your branch but pushed my master branch instead. This caused an empty diff on this PR, which lead Github to automatically close it. As long as the PR is closed I cannot push to your branch to fix my mistake and as long as the diff is empty I cannot re-open the PR. I took the simple solution of opening a new PR with these changes. Please check out #139. If it looks good to you, I will merge it.

I think it is fine to me