Small fixes for CAN
stm32-rs/stm32f3xx-hal pull request #186
Opened 2020-12-20 22:17 UTC by zklapow

I know there is an open issue for refactoring the CAN impl (#178) but figured I would patch the existing impl slightly in the meantime.

This fixes an issue where weren't actually transmitting the correct length of data, as well as adding options to allow users to configure the baud rate and enable loopback mode.

2020-12-20 22:21 UTC, Sh3Rm4n commented
Don't worry about #178 too much. This is still very WIP and for now only contains added TODO comments. More of a reminder for myself. Maybe I should close that PR until it contains some useful changes.

2020-12-20 22:35 UTC, Sh3Rm4n requested changes

2020-12-20 22:35 UTC, Sh3Rm4n commented on src/can.rs
> +/// Use `CanBitRateOpts::default()` to get 250kbps at 32mhz system clock
```suggestion
/// Use `CanOpts::default()` to get 250kbps at 32mhz system clock
```

2020-12-20 22:35 UTC, Sh3Rm4n commented on src/can.rs
> +}
I'm not a big fan of this approach. 

Configuring via integer values does not really guide a user of this crate towards a correct and comprehensible configuration of this peripheral, and it does lead to having many magic values in the code. 

Maybe use enums, possibly leveraging the already existing enum types provided by [stm32-rs] use the [builder-pattern](https://github.com/rust-unofficial/patterns/blob/master/patterns/builder.md)? 

[stm32-rs]: https://docs.rs/stm32f3/0.12.1/stm32f3/stm32f303/can/btr/index.html

2021-01-10 20:36 UTC, zklapow commented
updated this to use a builder + the source enums where possible.

2021-01-16 17:14 UTC, zklapow commented
(also didnt realize the clippy lints were failing, fixed now)

2021-03-02 21:23 UTC, Sh3Rm4n requested changes
Sorry for the long delay on my side again. I've to figure out to devote some time regularly to this project. The last active maintenance efforts of myself are reduced to short bursts. 

Some very minor nits, the rest looks ok to me. As `Can::new()` has the same API as before, this is not API break. Changelog entries are always welcome, but in this case not required.

In the long run, we should think about using the https://github.com/stm32-rs/bxcan types, 
and in the longer run, see if we can copy / merge some ideas from https://github.com/stm32-rs/stm32f1xx-hal/pull/293. 

But this takes time. As of now, I'm really happy, that you are doing this work on the CAN peripheral right now! :)

2021-03-02 21:23 UTC, Sh3Rm4n commented on src/can.rs
> +    pub fn lbkm(mut self, lbkm: LBKM_A) -> Self {
Maybe reexport the `LBKM_A` type, so that the user does not have to dig through the stm32::can abstractions to find the correct enum.

2021-03-02 21:23 UTC, Sh3Rm4n commented on src/can.rs
> +    /// Initialize the CAN Peripheral
Minor nit: In this comment you could mention, that the options are implicitly created by `CanOpts::default()`, as I find this information particularly useful to know here. 

Maybe something like  

```suggestion
    /// Initialize the CAN Peripheral
    /// 
    /// The CAN peripheral is configured according to `CanOpts::default()`.
    /// If you want to explicitly set the configuration, use `Can::new_with_opts()` instead.
```

2021-03-03 14:51 UTC, zklapow commented
no prob @Sh3Rm4n I am in the same boat myself. I find occasional bouts of time to work on this, but much less than I would prefer!

I will make some of those changes later today and update the changelog as well.

I totally agree about using `bxCan`, I was looking for something like that to exist when I originally started work on this! I have been meaning to give that a go, but have been hesitant to mess with it because I have been using the existing CAN stuff for a motor driver I am building and didn't want to mess with it. I might give it a go soon though.

2021-03-03 20:25 UTC, Sh3Rm4n commented
> I will make some of those changes later today and update the changelog as well.

Nice :+1: 

> I totally agree about using bxCan, I was looking for something like that to exist when I originally started work on this! 

Yeah, I know that your original work on CAN predates the `bxCAN` crate. It's nice to see the eco-system improving :)

> I have been meaning to give that a go, but have been hesitant to mess with it because I have been using the existing CAN stuff for a motor driver I am building and didn't want to mess with it.

No pressure. Maybe some else has time to pick this up and you can focus on your motor driver! :)

2021-03-05 07:11 UTC, Sh3Rm4n approved these changes
LGTM

Do want to add anything or can I merge it?

2021-03-05 15:03 UTC, zklapow commented
Should be good to merge!

2021-03-07 19:14 UTC, merged